# Generated by Django 6.0.6 on 2026-06-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('value', models.TextField(blank=True)),
                ('setting_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('textarea', 'Textarea'), ('color', 'Color'), ('email', 'Email'), ('url', 'URL'), ('phone', 'Phone')], default='text', max_length=20)),
                ('group', models.CharField(choices=[('general', 'General'), ('branding', 'Branding'), ('contact', 'Contact'), ('social', 'Social Media'), ('background', 'Background'), ('footer', 'Footer'), ('seo', 'SEO'), ('custom', 'Custom')], default='general', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'order'],
            },
        ),
    ]
