# Generated by Django 6.0.6 on 2026-06-16 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('kelas_libur', 'Kelas Libur'), ('perubahan_jadwal', 'Perubahan Jadwal'), ('penggantian_ruangan', 'Penggantian Ruangan'), ('informasi_uts', 'Informasi UTS'), ('informasi_uas', 'Informasi UAS'), ('informasi_akademik', 'Informasi Akademik'), ('berita', 'Berita'), ('umum', 'Umum')], default='umum', max_length=50)),
                ('audience', models.CharField(choices=[('all', 'Semua'), ('mahasiswa', 'Mahasiswa'), ('dosen', 'Dosen'), ('admin', 'Admin'), ('class', 'Per Kelas')], default='all', max_length=20)),
                ('is_important', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('attachment', models.FileField(blank=True, upload_to='announcements/')),
                ('pinned_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class')),
            ],
            options={
                'ordering': ['-is_important', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
